### PR TITLE
Depth scaling parameter

### PR DESCRIPTION
**Pull request by stwirth**
This pull request adds a parameter for depth scaling, called "z_scaling". Together with the already present parameter "z_offset" it is possible to "correct" depth values using a linear function of type `y=ax+b`. Instead of full stereo-like calibration one can use these parameters to compensate for bad (factory-) focal length calibration of the IR camera.
The following graph shows depth measured using a checkerboard detection & solvePnP in the RGB image (mean z of all checkerboard corners) on the y axis and the corresponding depth of the depth image on the x axis together with a fitted line for one of our Asus XtionPRO Live cameras.

Screenshot from 2013-04-15 16:08:53

### CODE REVIEW

**Comment by jkammerl** [comment]
Is there are depth scaling parameter that works for the Asus device as well as for the Kinect? If so, it would be interesting to set this as the default value.

**Comment by stwirth** [comment]
I didnt' test any Kinect yet and testing several different Asus that we have here is still pending. I don't know if a default makes sense as it changes when you calibrate the RGB camera and it would break backwards compatibility of the data interpretation.

**Comment by stwirth** [comment]
Any concerns about accepting this pull request?

**Comment by jonbinney** [comment]
It looks like the default behavior will be the same as before, so it looks fine to me. What do you think @jkammerl ?

**Comment by jkammerl** [comment]
Yeah, looks fine! Thanks Stephan!

**Pull request merged**
