### PR TITLE
Fix compilation on OS X 10.9 (or anywhere else with a C++11 compiler)

### PR DESCRIPTION
**Pull request by NikolausDemmel**
unique_lock and friends is ambigious when using namespace std and boost, at
least with C++11.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
ping

**Comment by jonbinney** [comment]
Builds for me on hydro/ubuntu 13.04, and doesn't change any behavior, so merging.

**Comment by jonbinney** [comment]
@NikolausDemmel there's no need to do a release right?

**Comment by NikolausDemmel** [comment]
Hm... without a release it will continue to not build on (recent) OS X. With this patch it does build: http://answers.ros.org/question/158546/openni-and-kinect-on-hydro-osx-108/?answer=164226#post-id-164226

**Comment by NikolausDemmel** [comment]
Guess what I wanted to ask is: is there any reason not do do a release (soon-ish)?

**Comment by jonbinney** [comment]
Why would a release affect OS X? Aren't you building from source?

**Comment by jonbinney** [comment]
The reason for not releasing is laziness...

**Comment by NikolausDemmel** [comment]
Ah I understand, that is a valid reason.

On OS X we are building from source, but even when building from source (on any platform), the default way is using `rosinstall_generator` to pull in the sources of the latest release, not HEAD. So it would still require everyone to pull in the patches manually.

It therefore would be great if a release could happen in the near future (not super urgent, though).

**Comment by NikolausDemmel** [comment]
Thanks!

**Comment by jonbinney** [comment]
Yeah, should be a release soonish. Bye the way, have you tried openni2_camera? I think it gets more attention now, and will probably work better.

**Comment by NikolausDemmel** [comment]
I will have to try that some time, thanks for the hint.

**Comment by 130s** [comment]
Is this worth forward-ported into `indigo-devel`?

**Comment by jonbinney** [comment]
@130s Possibly, but really this package just needs a new maintainer. The listed maintainer is no longer working on related things. @130s, are you interested? :-P

**Comment by 130s** [comment]
Sure, I can do release tasks and review non-functional changes. I have to ask others for reviewing functional changes though. If that's ok please add me write access to this and the release repositories.

**Comment by jonbinney** [comment]
@130s  you've now got write access to the source and release repos. Let me know if you run into any permissions problems. You should add yourself as maintainer in the `package.xml` as well.

**Pull request merged**
