### PR TITLE
Remove unneeded dependency (libopenni-sensor-primesense-dev is an internal plugin).

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
Please cherry-pick this and `f110b5f` into indigo-devel as well.

**Comment by trainman419** [comment]
I'm not convinced that this is unnecessary. I think the libopenni-sensor-primesense package includes some udev rules which generally make life easier for most developers.

**Comment by jspricke** [comment]
The build dependency is unnecessary. The run dependency would be a recommends, at most (that's what we have in libpcl-1.7-bin for example). Also I would propose to recommend the virtual libopenni-sensor package instead, as it allows to choose other drivers as well.

**Comment by 130s** [comment]
Triggering travis by close-reopen.

**Comment by jspricke** [comment]
@130s it's not enough to do a close and reopen, the `.travis.yml` needs to be in in this branch. I can rebase it, if you want but given that `indigo-devel` is the default now and that it's a trivial change, I would propose you simply do it yourself. Otherwise I can send a new pull request as well.

**Comment by 130s** [comment]
@jspricke I see. In fact in `hydro-devel` there's no travis config yet. I know many users (mostly in schools) still use older distros, so I personally try to maintain compatibility in source.

And should we merge this?

**Comment by jspricke** [comment]
It would be great to have this merged because you currently breaking support for the Kinect with it.

**Pull request merged**
