### PR TITLE
Data skip should not be limited to 10

### PR DESCRIPTION
**Pull request by fmder**

### CODE REVIEW

**Comment by 130s** [comment]
Triggering travis by close-reopen.

**Comment by 130s** [comment]
@fmder it's been awhile but could you give us a rationale of your change if you remember? Also if you could open this against `indigo-devel` that will be even greater.

**Comment by fmder** [comment]
I simply wanted to have an image every 2-3 seconds, since the Kinect was
running on a very slow device.

2015-10-17 11:52 GMT-04:00 Isaac I.Y. Saito notifications@github.com:

**Comment by 130s** [comment]
I see. 

+1
Since this is only increasing max value of the skip rate, I can't think of scenario where this becomes a breaker.

**Pull request merged**
